project_id = "eydqducvsddckhyatcux"

[functions.chat]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.identify-gender]
verify_jwt = false

[functions.analyze-lead-magnet]
verify_jwt = false

[functions.download-material]
verify_jwt = false
