project_id = "eydqducvsddckhyatcux"

[functions.chat]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.identify-gender]
verify_jwt = false

[functions.analyze-lead-magnet]
verify_jwt = false

[functions.download-material]
verify_jwt = false

[functions.import-contacts]
verify_jwt = false

[functions.import-leaders]
verify_jwt = false

[functions.update-contact-emails]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.test-zapi-connection]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.test-resend-connection]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.greatpages-webhook]
verify_jwt = false

[functions.generate-survey-questions]
verify_jwt = false

[functions.analyze-survey]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.test-smsdev-connection]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false
