project_id = "eydqducvsddckhyatcux"

[functions.chat]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.identify-gender]
verify_jwt = false

[functions.analyze-lead-magnet]
verify_jwt = false

[functions.download-material]
verify_jwt = false

[functions.import-contacts]
verify_jwt = false

[functions.import-leaders]
verify_jwt = false

[functions.update-contact-emails]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false
